version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      # xref: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
      ci:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      go:
        update-types:  ["minor","patch"]
    schedule:
      interval: "weekly"
      day: "sunday"
