# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
builds:
  - main: cmd/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
release:
  extra_files:
    - glob: output/install.yaml
    - glob: output/helm_chart.tar.gz
checksum:
  name_template: 'checksums.txt'
  extra_files:
    - glob: output/install.yaml
    - glob: output/helm_chart.tar.gz
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
# for more information on what this target does: https://goreleaser.com/errors/docker-build/
dockers:
  - id: linux-build
    image_templates:
    - "{{ .Env.REGISTRY }}/skarlso/crd-bootstrap-controller:{{ .Tag }}"
    - "{{ .Env.REGISTRY }}/skarlso/crd-bootstrap-controller:latest"
    # GOOS of the built binary that should be used.
    goos: linux
    # GOARCH of the built binary that should be used.
    goarch: amd64
    dockerfile: "{{ .Env.DOCKERFILE }}"
    build_flag_templates:
    - "--platform=linux/amd64"
