resources:
- manager.yaml
images:
  - name: controller
    newName: controller
    newTag: latest
  - name: skarlso/crd-bootstrap-controller
    newName: ghcr.io/skarlso/crd-bootstrap-controller
    newTag: latest
